apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-rep
spec:
  replicas: 5
  selector:
    app: selenium-chrome
  template:
    metadata:
      name: selenium-chrome
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: node-chrome
          image: selenium/node-chrome
          ports:
            - containerPort: 5555
          env:
            - name: HUB_HOST
              value: "selenium-svc"
            - name: HUB_PORT
              value: "4444"